name: vowel_counter_lib
description: Small library for counting vowels in a string.
version: 1.0.1
repository: https://github.com/allopez89/vowelcounterlib.git

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
